version: '3.5'
services:
  blockscout-db:
    container_name: blockscout-db
    image: postgres
    expose:
      - 5435
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command: ["postgres", "-N", "500"]

  blockscout:
      container_name: blockscout
      image: hermeznetwork/zkevm-explorer:latest
      ports:
          - 4010:4010
      volumes:
          - ../apps/block_scout_web/assets:/app/apps/block_scout_web/assets
          - ../apps/block_scout_web/lib:/app/apps/block_scout_web/lib
          - /app/apps/block_scout_web/assets/node_modules
      environment:
          - PORT=4010
          - NETWORK=POE
          - SUBNETWORK=Polygon zkEVM
          - CHAIN_ID=1401
          - COIN=ETH
          - ETHEREUM_JSONRPC_VARIANT=geth
          - ETHEREUM_JSONRPC_HTTP_URL=https://develop.zkevm-test.net:2083
          - DATABASE_URL=postgres://test_user:test_password@blockscout-db:5432/explorer
          - ECTO_USE_SSL=false
          - MIX_ENV=prod
          - LOGO=/images/blockscout_logo.svg
          - LOGO_FOOTER=/images/blockscout_logo.svg
          - SUPPORTED_CHAINS=[]
          - SHOW_OUTDATED_NETWORK_MODAL=true
          - OUTDATED_NETWORK_MODAL_TITLE=Welcome to the new Polygon zkEVM testnet! 
          - "OUTDATED_NETWORK_MODAL_MESSAGE_1=To connect, follow the instructions available at:"
          - OUTDATED_NETWORK_MODAL_URL_1=https://public.zkevm-test.net
          - "OUTDATED_NETWORK_MODAL_MESSAGE_2=The previous network is still available until January 5th. You can access using the information available at:"
          - OUTDATED_NETWORK_MODAL_URL_2=https://deprecated.zkevm-test.net
      command: ["/bin/sh", "-c", "mix do ecto.create, ecto.migrate; mix phx.server"]
